// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjmH8DHwOPRlqxz-oFn_0rshcv1B3AwW8',
    appId: '1:680606846267:web:47033bbe513ad34c1cfb1e',
    messagingSenderId: '680606846267',
    projectId: 'chatapp-3ef86',
    authDomain: 'chatapp-3ef86.firebaseapp.com',
    storageBucket: 'chatapp-3ef86.appspot.com',
    measurementId: 'G-167T1TDFWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRRdvlIVpNlCmanHSseKKKnE1iic_yd4',
    appId: '1:680606846267:android:b5ac23fe9bf446661cfb1e',
    messagingSenderId: '680606846267',
    projectId: 'chatapp-3ef86',
    storageBucket: 'chatapp-3ef86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSnc6vTcvgyxUzRgw7YMX4Th5XQD9axc',
    appId: '1:680606846267:ios:4fea6787c6d10bfc1cfb1e',
    messagingSenderId: '680606846267',
    projectId: 'chatapp-3ef86',
    storageBucket: 'chatapp-3ef86.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
